# Generated by Django 3.2.8 on 2021-10-23 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('city', models.CharField(choices=[('Bronx', 'Bronx'), ('Brooklyn', 'Brooklyn'), ('Cedarhurst', 'Cedarhurst'), ('Flushing', 'Flushing'), ('Jackson Heights', 'Jackson Heights'), ('Manhattan', 'Manhattan'), ('New York', 'New York'), ('Queens', 'Queens'), ('Staten Island', 'Staten Island')], max_length=20)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=7)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(choices=[('Bronx', 'Bronx'), ('Brooklyn', 'Brooklyn'), ('Cedarhurst', 'Cedarhurst'), ('Flushing', 'Flushing'), ('Jackson Heights', 'Jackson Heights'), ('Manhattan', 'Manhattan'), ('New York', 'New York'), ('Queens', 'Queens'), ('Staten Island', 'Staten Island')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Inferma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=64)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inferma', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=16)),
                ('choice_id', models.CharField(blank=True, max_length=7, null=True)),
                ('initial', models.BooleanField(default=False)),
                ('inferma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.inferma')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='core.patient'),
        ),
    ]
