# Generated by Django 3.2.8 on 2021-10-14 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Inferma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=32)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inferma', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=16)),
                ('choice_id', models.CharField(max_length=7)),
                ('initial', models.BooleanField(default=False)),
                ('inferma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.inferma')),
            ],
        ),
    ]
