# Generated by Django 3.2.8 on 2021-10-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='unit',
            field=models.CharField(max_length=64),
        ),
    ]
