# Generated by Django 3.2.8 on 2021-10-14 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211014_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferma',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
