# Generated by Django 3.2.8 on 2021-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inferma_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='choice_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
