sex_choice = (
    ("male", "Male"),
    ("female", "Female"),
    ("others", "Others")
)

evidence_choice = (
    ("present", "present"),
    ("absent", "absent"),
    ("unknown", "unknown")
)

all_tests = {
    "allergologists": ["RBC Count", "WBC Count"],
    "dermatologist": ["RBC Count", "WBC Count", "Urine test"],
    "psychologist": [ "RBC Count", "WBC Count"],
    "gastroenterologist": ["RBC Count", "WBC Count"],
    "ophthalmologist": ["RBC Count", "WBC Count"],
    "general practitioner": ["RBC Count", "WBC Count", "BP Test"],
    "cardiologist": ["ECG", "Cardiac Output", "Stroke Volume", "Heart Rate"],
    "pulmonologist": ["Spirometry", "Pulse Oximetry"],
    "surgeon": ["Urinalysis", "ECG", "WBC Count", "Complete Blood Count", "Blood Coagulation Test (PT/PTT)", "Glucose and Potassium Test"],
    "gynecologist": ["RBC Count", "WBC Count", "Urine Test"],
    "endocrinologist": ["RBC Count", "WBC Count"],
    "rheumatologist": ["Erythrocyte Sedimentation Rate (ESR)", "CRP RBC Count", "WBC Count"],
    "urologist": ["RBC Count", "WBC Count", "Urine test"],
    "nephrologist": ["RBC Count", "WBC Count", "Creatinine Test", "Urine Test"],
    "hematologist": ["RBC Count", "WBC Count", "Haemoglobin Count", "Platelets Count", "Hematocrit test"],
    "oncologist": ["CBC count"],
    "diabetologists": ["BP Test", "Lipid Profile", "Sugar Test"],
    "infectiologist": ["RBC Count", "WBC Count"],
    "pediatrician": ["RBC Count", "WBC Count", "Urine Test"],
    "toxicologists": ["RBC Count", "WBC Count", "Urine Test"]
}

specialists = {
    "bronx": {
      "allergologists": [
        "Ajay Shah",
        "John Maese",
        "Mariamma G. Chelagiri",
        "WON SOHN",
        "David Chiang",
        "RICHARD BELLI",
        "Nayaz Ahmed",
        "Jose Goris",
        "Mindy Weiss",
        "Austin Chen",
        "Paul Nacier",
        "Dolores Martinez",
        "Rivka Stein",
        "Emilio Villegas",
        "Steven Barkoff"
      ],
      "oncologist": [
        "Yeoman Chan",
        "Gabriel Gustin",
        "Franklyn Sencion",
        "Wenjing Zhou",
        "James Blake",
        "Lewis R. Lipsey",
        "Cynthia Krause",
        "Sharon Zheng",
        "Xiaxi HU",
        "Kuldip Sachdev"
      ],
      "dermatologist": [
        "Alex Bruckstein",
        "Mario Saint-Laurent",
        "Hillary Bell",
        "Ching-Yin Lam",
        "Weiguo Lin",
        "Jonathan Leung",
        "Rodolfo Miranda",
        "Ari Klapholz",
        "Kotresha Neelakantappa",
        "Jermel Hawkins",
        "Stephanie Chambers",
        "Pulle Dunstan Ferando"
      ],
      "pediatrician": [
        "Anna DiBona",
        "Sarat Bhumi MD",
        "Durga Maddineni",
        "Hifza Qureshi",
        "Abeer Dabbas",
        "Syed Hussaini",
        "Christel Moran",
        "Mitchell Adler",
        "Raji Ayinla",
        "Lawrence Herman",
        "Elbert St. Claire, III",
        "Shirley Li",
        "Zurab Abayev",
        "Robert Zaloom",
        "Leslie Alvarado",
        "Laura Dattner",
        "Azra Wasti",
        "Subha Atluri"
      ],
      "rheumatologist": [
        "Nair Ramachandran",
        "Jamshad Wyne",
        "Rafael Rodriguez",
        "Shabana Azam",
        "San Shih",
        "David Gomez",
        "Leonid Chernov",
        "Junaid Chohan",
        "Paul De Guzman",
        "Thao Ngo",
        "Alix Dufresne",
        "Saul Feldman",
        "Holson S. Hector"
      ],
      "surgeon": [
        "Veronika Romashova",
        "Stella Ilyayeva",
        "Mitchell Locke",
        "Franklyn Sencion",
        "Patrick Dalton",
        "Dang Nguyen",
        "Danielle Ogopozo",
        "Lucille L. Pak",
        "Patricia Mullings",
        "Archana Singiri",
        "Alex Wright",
        "Alan Ross"
      ],
      "pulmonologist": [
        "M. Fawzy Saleem",
        "Fazlul Yusuf",
        "Alexander Krishtul",
        "Jay Cowan",
        "Felix Florimon",
        "Gladstone Gunnis",
        "Eric Zhou",
        "Henry Sardar",
        "Saul Feldman",
        "Haleh Mohseni"
      ],
      "hematologist": [
        "Tahira Farooqi Ghaffar",
        "Yong S. Tak",
        "Maggie Bertisch",
        "Timothy Johnson",
        "Edward Chan",
        "Caroline Collado",
        "Irina Fuchs",
        "pervaiz iqbal",
        "David Fagan"
      ],
      "gastroenterologist": [
        "Emmanuel Fashakin",
        "Ernst Jean",
        "Michelle K Samuels"
      ],
      "toxicologists": [
        "Syed Najeeb Hussaini",
        "John Wat",
        "Louis Heisler",
        "Elsa Sofia Reynoso",
        "Lilia Gorodinsky",
        "Sandy Cheung",
        "Fausto Gonzalez",
        "Robert Murayama-Greenbaum",
        "Roland Nyein",
        "Oleq Davie",
        "Rachelle Namm",
        "Mohamad Erfani"
      ],
      "psychologist": [
        "Pin Mei Yao",
        "Kent B. Cao",
        "Elaine Alvarez",
        "Delys St. Hill",
        "Monic Kim",
        "Leung Wing Wong"
      ],
      "urologist": [
        "Kyi Win Yu",
        "Jose Fulgencio-Delmonte",
        "Leonid Bukhman",
        "Frederick Ast",
        "Caryn Selick",
        "Ethan Ciment",
        "Michael Sabido",
        "Anthony R. Sgarlato",
        "Singmay Siu",
        "Eldawary Wael",
        "Javid Yadegar",
        "Craig A. Kaiser",
        "Samia Tayab",
        "Vinod Bhagat"
      ],
      "diabetologists": [
        "MOHAMMAD AKHTAR",
        "Pervaiz Qureshi",
        "Daniel Izon",
        "Edwin Chan",
        "John Delloso",
        "Jee Sook Lee",
        "Cynthia Myers",
        "victor Mok",
        "Elizabeth Cruz",
        "Ijaz Ahmad",
        "Manana Petrov",
        "Velko Voynov",
        "Iqbal Merchant",
        "Richard Steiner"
      ],
      "cardiologist": [
        "Nuzhat Faridi",
        "Michelle Jacobs",
        "Hector Holson",
        "Hla Tun",
        "Mary Noecker",
        "Dean Fong",
        "PCP TBD",
        "Liu Zhechun",
        "Terry Blackett-Bonnett",
        "Vincent Dowling",
        "Mark Lew",
        "Mario Saint-Laurent",
        "Rafael Bueno",
        "S Gandhi"
      ],
      "general practitioner": [
        "Roxanne Hobbs-Green",
        "Caesar Preposi",
        "Jean Carlos Torres",
        "Naomi Molner",
        "Sandra Rosado",
        "Maria Evola",
        "Benjamin Barrah",
        "Lionel Lefevre",
        "Grace Dworan",
        "Alisa Minkin",
        "Veena Chadda"
      ],
      "ophthalmologist": [
        "Muntaz Majeed",
        "Alexander Morden",
        "Anita Ong Hui",
        "Luis Ortega",
        "Mayra Mahadin",
        "Yanhan Huang"
      ],
      "endocrinologist": [
        "Jean-Robert Boursiquot",
        "Yuderqui Checo",
        "Sameera Haroon",
        "Marie-Lourdes Roche",
        "Ling Ling Zeng",
        "Olga Belostotsky",
        "Mara Pulcher",
        "Van Hong Nguyen",
        "Perminder Dhillon",
        "Lalit Patel",
        "Ainsley Pennant",
        "Ronald Jacques",
        "Tatyana Gabinskaya",
        "Daniel Reich"
      ],
      "infectiologist": [
        "Katherine Zeng",
        "Yasmine Arasta",
        "Larry Shemen",
        "Clotilde Pena",
        "Mordechai Beityakov",
        "Rafael Guillen",
        "Rudabah Hasan",
        "Paulu Pina"
      ],
      "nephrologist": [
        "Monique Apollon",
        "Jennifer Figueroa",
        "MeeYee Yolanda Eng",
        "Jeffrey Teitelbaum",
        "Rita Ahuja"
      ],
      "gynecologist": [
        "Sayera Haque",
        "Elaine Brown",
        "Neera Ahuja",
        "Francis DeVito",
        "Ella-Jean Richards"
      ]
    },
    "brooklyn": {
      "nephrologist": [
        "Nicole Arcentales",
        "Ida Tetro",
        "Felicitas Santiago",
        "Gunwant Singh",
        "Thomas Chen",
        "Zia Ahmed",
        "Tinatin Urphanishvili",
        "Rosalinda Spatoliatore",
        "John Munoz",
        "JOHN CAHILL",
        "Gloria Florez",
        "Rawand Khader"
      ],
      "infectiologist": [
        "Alexander Beylinson",
        "Hector Becil",
        "PANKAJ MAMTORA",
        "Franz Goyzueta",
        "Kuo Nan-Hsien",
        "Tumika Williams Wilson",
        "Claude Pericles",
        "Abdul Malik",
        "Sudha Patel",
        "Carole Dubuche",
        "Oded Preis",
        "Guo Yong Dai",
        "Lucy Palomino",
        "Provat Das",
        "Shervin Mortazavi"
      ],
      "endocrinologist": [
        "Jaxier Chacon",
        "Jean Langhans",
        "Ramakrishnayya Pattumudi",
        "O'Neall E. Parris",
        "Todd Linden",
        "Emil Baccash",
        "Haroutyoun Margossian",
        "Laeeq Ahmad",
        "Israel Bochner",
        "David Weiss"
      ],
      "gynecologist": [
        "Alex Racco",
        "Mohammad Bhatti",
        "Daniel Boccardo",
        "Jeffrey Belmon",
        "Stephen Dillon",
        "Suresh Hemrajani",
        "Indira Kairam",
        "Naveen Pesala",
        "Larisa Veksman",
        "Muhammad Dogar",
        "Yelena Karasina",
        "M Laporte",
        "Yuliya Giyaur",
        "GARY ABBERBOCK",
        "Cary Pollack"
      ],
      "allergologists": [
        "Kevin Charlotten",
        "Michael Landor",
        "Olga Falkowski",
        "Eliscer Guzman",
        "Mark Horowitz",
        "Arthur Maisto",
        "Ramon Ferrand",
        "Zuheir Said",
        "Sherill Purcell",
        "Yvette Ortiz"
      ],
      "toxicologists": [
        "Marjorie Dugue",
        "Donna Murphy",
        "Nazmul Hossain Khan",
        "Wai-kuen Lam",
        "Amanda Valencia",
        "Daniela Atanassova-Lineva",
        "Jack Bruder",
        "Rafael Barranco",
        "Xin Pang",
        "Ludmila Sedlackova",
        "Julie Hurtado",
        "Rosemarie Pezzulo"
      ],
      "pediatrician": [
        "Gloria Dunnder Leacock",
        "Diego Ratzlaff",
        "Reno DiScala",
        "MOHYUDDIN QURESHI",
        "Nathaniel Brownlow",
        "Shazah Khawaja",
        "Sandra Garcia",
        "Kyi Win Yu",
        "Terry Blackett-Bonnett",
        "Fernando A. Ginebra",
        "Luis Blanco",
        "Maria Perea-Barbosa"
      ],
      "diabetologists": [
        "Yi Ngai",
        "George V Jhagroo",
        "Cherenfant Lucot",
        "George McMillan",
        "Udele Taylor-Randall",
        "Diego Ponieman",
        "Betty Punzalan",
        "Haydee Blanca",
        "Kevin Armington",
        "Lin Gong",
        "Verlaine Brunot",
        "Sonia Vinas",
        "Marievic Villanueva",
        "Aurea Quiroz"
      ],
      "surgeon": [
        "Rumana A. Rahman",
        "Alexandra Altchek",
        "Nayaz Ahmed",
        "Sudhanshu Narendra",
        "Patricia Leone",
        "Yuderqui Checo",
        "Zahava Miller",
        "Himanshu Goel"
      ],
      "pulmonologist": [
        "Shamim Ahmed",
        "Thomas Lyo",
        "Bina Chaudhari-Mody",
        "Anthony G. Purpura",
        "Charles Brum",
        "Carl Franzetti",
        "Jeremy Gutwein"
      ],
      "hematologist": [
        "CANDIDA CATUCCI",
        "Olga Echeverria",
        "Wilfredo Lao",
        "Emilio Villegas",
        "JI-QING WEI",
        "Joseph Roosevelt Clerisme",
        "Michael Correa",
        "Howard J Rosman",
        "Llewellyn Hyacinthe",
        "ROBERT TAGLIA"
      ],
      "gastroenterologist": [
        "Richard Perrin",
        "Alison Amsterdam",
        "Muhammad M. Haque",
        "Angela Hon",
        "Gary Mucciolo",
        "Timothy Wong",
        "Adebola Orafidiya",
        "Emilia Pollack",
        "Prudence Osei-Tutu",
        "Vijay Alla",
        "Angelo D. Michilli"
      ],
      "general practitioner": [
        "Camille Philippe",
        "Rabeya Chowdhury",
        "ARTHUR DOVE",
        "Anthony Starpoli",
        "Jose Vargas",
        "Calvin Chin",
        "Blanche Mercedes",
        "Ivan Herstik"
      ],
      "psychologist": [
        "Marina Reznitsky-Royzman",
        "Austin Lu",
        "Nadia Duvilaire",
        "Buddhadev Manvar",
        "Bin Yang",
        "Mohammed Yousufuddin",
        "Chaim Backman",
        "Jill Groves",
        "Ramon Tallaj"
      ],
      "rheumatologist": [
        "Marc Yunis",
        "Ibrahim Carvan",
        "Kennedy Omonuwa",
        "Luis Astudillo",
        "Veeraf Sanjana",
        "Machlah Lopiar",
        "Brianne O'Connor",
        "Vandana Patil",
        "Ana Olivero"
      ],
      "cardiologist": [
        "Mary X. Hu",
        "Chixin Fang",
        "Syed Hassan",
        "Virginia Martinez",
        "Rajendra RAMPERSAUD"
      ],
      "urologist": [
        "Eloisa Acosta",
        "Jack Levine",
        "Carmen Cardona",
        "Lucien Mocombe"
      ],
      "ophthalmologist": [
        "Arturo Caesar",
        "Mariana Marcu",
        "Ishita Thakkar",
        "Yaacov Weiss",
        "Howard Eisenstein",
        "Boris Sagalovich",
        "Harvey Mermelstein",
        "Domenic Onyema",
        "Melchor Domingo",
        "Zhang Jian"
      ],
      "oncologist": [
        "Loren Greene",
        "Wuhua Jing",
        "Mayreen Kelleher",
        "David Cotos-Mejia",
        "Tze On Poon",
        "Carmen Lazala"
      ],
      "dermatologist": [
        "Eileen Hoffman",
        "Raymond Yung",
        "Marrissa Pelletier",
        "Antoine Fernaine",
        "Lalitha Reddy",
        "Andy Hu",
        "Christina Guillen",
        "Marcia Pehr",
        "Michael Ader",
        "Clotilde Pena"
      ]
    },
    "cedarhurst": {
      "infectiologist": [
        "Donald McCord",
        "Rounak Ahmed",
        "Fei Wang",
        "Priya malik",
        "Mohammed M. Rahman",
        "Maria Molina",
        "George Klein",
        "Elizabeth Schwartzburt",
        "DMITRY KONSKY",
        "Joseph Paul",
        "Francois G. Tellus",
        "Rosemarie St. Victor",
        "Fausto Gonzalez"
      ],
      "endocrinologist": [
        "Giovannie Jean-Baptiste",
        "Victor Peralta",
        "Annette Perea",
        "Hari Krishna Shukla",
        "Dyan Hes",
        "Vincent Pedre",
        "Daniel Zanger",
        "Muhammad S. Alam"
      ],
      "surgeon": [
        "Lenard Marchetta",
        "Eneida Agosto",
        "Arpana Modi",
        "Kazuko Ko",
        "Victoria Katz",
        "Jenny Liu",
        "Jordan Wong",
        "Boris Chusid"
      ],
      "hematologist": [
        "Viola Ortiz",
        "Qaiser Abbas",
        "William Ankobiah",
        "Ellimottil Kuriakose",
        "Eliahu Samra",
        "Damaris Collado",
        "Naginder Puri",
        "Magdalena Cadet",
        "Nedjie Pierre",
        "Cathy Delerme-Pagan",
        "Charity Fancis-Munson",
        "Ofem Ajah",
        "Yelena Vayntrub"
      ],
      "pediatrician": [
        "Anna Marie Scopellito-Olsen",
        "Nuzhat Syed",
        "Candido Norberto",
        "Elizabeth Salzer",
        "Suraj Tikko",
        "Geraldo Lombardo",
        "Carmen Runiga-Kartachou",
        "Arsenio Miguel Tio",
        "Chaim Wanounou",
        "Chaim Wanounou",
        "Isadore Gutwein"
      ],
      "dermatologist": [
        "David Fastman",
        "Xiandong Shi",
        "Hector Holson",
        "Aaron Berger",
        "Salvatore Degliuomini",
        "Jing Jing Ao",
        "Manuel Mejia",
        "Leonardo Vando",
        "Pramila Kolisetty"
      ],
      "gynecologist": [
        "Nataly Larson",
        "Erie Agustin",
        "Yuping Chen",
        "Daniel Wasserman",
        "Rehana Sajjad",
        "Alice Lau",
        "Paul Knoepflmacher",
        "Haleh Milani",
        "Konstantinos Zarkadas",
        "Syed Z. Hussaini",
        "Hinda Krumbein",
        "P Milord",
        "EMMANUEL PEPRAH",
        "Arnold Wilson"
      ],
      "oncologist": [
        "Khurram Awan",
        "Ferdous Khandker, MD",
        "Sudha Vijaykumar",
        "Hemant Patel",
        "cindy chen",
        "Ching Sum Leung",
        "Natalia Peters",
        "Dina Kornblau"
      ],
      "psychologist": [
        "Jia Hong",
        "STELLA MILOS",
        "Saulius Skeivys",
        "Tak Chan",
        "Marissa Santos",
        "Payman Jarrahy",
        "Thangamuthu Arumugam",
        "Elizabeth Woodford"
      ],
      "general practitioner": [
        "Andrew Kim",
        "Amy Xioa Chen Ma",
        "Lyudmila Sorekin",
        "Marlene Saint-Hilaire",
        "Karen Chiu",
        "Juan Estevez"
      ],
      "cardiologist": [
        "Bernard Levine",
        "Suzanne Walker",
        "Wilson Chau",
        "Rohini Thodge",
        "Stacy Kreiswirth",
        "James Lax",
        "Michael Gehl",
        "Sara Donnelly",
        "Jose Perez",
        "Uzoma Okorrie",
        "Donna Simmons",
        "Nereida Correa"
      ],
      "gastroenterologist": [
        "Joseph Frager",
        "Zhu-Ping Zhou",
        "Maria Duran-Soriano",
        "Helen Hsieh",
        "Laurence Turnier-Antione",
        "Juan Tapia-Mendoza",
        "Lise Vincent",
        "Jiang Ming",
        "Susan Merguerian",
        "Prakash Kancherla"
      ],
      "urologist": [
        "MUHAMMAD BILLAH",
        "Afshin Tavakoly",
        "Eugene (Chien K.) Chiang",
        "Richard Myint",
        "Erin Dalton"
      ],
      "diabetologists": [
        "Hua Ding",
        "Rakesh Gupta",
        "Marie-Paule Dupiton",
        "Howard Naas",
        "Anna Saporito",
        "Frank Babb",
        "Barbara Medlin",
        "John F. Lazzara",
        "Hui Er Teng",
        "Bing Lu",
        "Imtiyaz Kapadwala",
        "Mercy Brew"
      ],
      "toxicologists": [
        "Carl Guillaume",
        "Urmila Shivaram",
        "Helen Cheung",
        "Dominic Moccia",
        "Jose Perez",
        "Terence Hsuih",
        "Arkadiy Izrailov",
        "Olga Tyuleneva",
        "Roger Villi"
      ],
      "allergologists": [
        "Ginny Leva",
        "Richard Shepard",
        "Bernadette Clement",
        "Chyne C. Tan",
        "Shaikh M. Hasan",
        "Victoria Katz",
        "Steven J. Goldstein",
        "Moshe Lazar",
        "Leonore Max"
      ],
      "nephrologist": [
        "Paul Lombardi",
        "Vincent Yeung",
        "Adedokun Akinyooye",
        "Alberto Tan",
        "Natalie Wilson",
        "Timothy Au",
        "George Fernaine",
        "Ronnie Chiu",
        "Ravindra Goyal",
        "Babu Jasty",
        "Simcha Ben-David",
        "Giancarlo Guido"
      ],
      "ophthalmologist": [
        "GUSTAVO MELAMEDOFF",
        "Mikhail Pinkhasov",
        "Jaime Roman",
        "Magalie Alfred",
        "Brena M. Desai",
        "CARLA LUCACEL",
        "YAO QIKAI",
        "Judy Marren",
        "Shuk-Yi Lee",
        "Sarah Ponce",
        "Flor, De La Cadena",
        "Maria Pirraglia",
        "Leonid Bukhman",
        "Chaya Stern",
        "Maja Zeric",
        "Mihir Basu"
      ],
      "pulmonologist": [
        "Zaw Oo",
        "Elizabeth Avaricio",
        "Patricia Herko",
        "Carmina Rivera",
        "Papanna Ravichandra, MD",
        "Jesika Shah",
        "Nisha Patel"
      ],
      "rheumatologist": [
        "Newsha Ghodsi",
        "David Hosten",
        "Xian Min Li",
        "Most Jahan Begum",
        "James Gough",
        "Elizabeth G. Campos",
        "Alcedo Cruz",
        "Richt Ligsay"
      ]
    },
    "flushing": {
      "general practitioner": [
        "Aldo Arpaia",
        "Song Ja Choi",
        "Ferdausi Hassan",
        "Tina Dobsevage",
        "Margaret Kearns-Stanley"
      ],
      "diabetologists": [
        "Michael Bruno",
        "Susan Fitzmaurice",
        "Max Francois",
        "Paul Lee",
        "Wei Wang",
        "Thomas Bustros",
        "MOHAMMAD CHHIPA"
      ],
      "pulmonologist": [
        "Vincent Calamia",
        "Tahira Ghaffar",
        "Norman Lee",
        "Himanshu Pandya",
        "Shelly Shi",
        "Babubhai Patel",
        "Priyanka Gupta",
        "Fu Fu He",
        "Aylin Kiyici",
        "Hector Valencia"
      ],
      "gastroenterologist": [
        "Claudia Geris",
        "Ghanshyam Bhambhani",
        "Arun Palkhiwala",
        "CHAUDHRY GHUMMAN",
        "Elisabeth Immanuel-Alexis",
        "Erica Amianda",
        "Simon Fensterszaub",
        "April Lowry",
        "Syed M. Hussaini",
        "Gaston Sterlin"
      ],
      "psychologist": [
        "Robert La Penna",
        "SURENDRA SUGRIM",
        "Jessica Borrero",
        "Marina Alayev",
        "Denise West",
        "Mark Joseph",
        "Sofya Kostanyan",
        "Alexander Merson",
        "Miksha Patel",
        "S Tokar"
      ],
      "gynecologist": [
        "James Laffertey",
        "Marco A. Garcia",
        "Alex Wei",
        "Marcia Nelson",
        "Mindy Galagher",
        "Nina Chao"
      ],
      "pediatrician": [
        "Furqan Tejani",
        "Karen Allison",
        "Svetlana Prokhorova",
        "Caroline Coccado",
        "Yick Moon Lee",
        "Albert A. Benchabbat",
        "Subash Malhotra",
        "Baah Asante"
      ],
      "toxicologists": [
        "Rudrama Duggirala",
        "Arumugan Vasanthi",
        "Mario Saint-Laurent",
        "Dorene Soo-Hoo",
        "Aline Benjamin",
        "Ashoke Kumar Das"
      ],
      "rheumatologist": [
        "Mery Gomez",
        "Fawzia Kazmi",
        "Arthur Kaplan",
        "Dana Shani",
        "Ka Li",
        "Jorge Serje",
        "Subodh Datta"
      ],
      "surgeon": [
        "Violet Abemayor",
        "Afroz Pervin",
        "Steven Straus",
        "Nurun N. Yusuf",
        "Pedro Guzman",
        "Jimmy Wong",
        "Yusuf Mamdani",
        "Kalpana Master",
        "Christopher Phang",
        "Jitendra Patel",
        "Zihe Shan",
        "Xin Yu Zhao"
      ],
      "nephrologist": [
        "Obiora Anyoku",
        "Ida Bronfman",
        "Pedro Kourtesis",
        "Edgar Flores-Castillo",
        "Richard Chan",
        "Zia Ghavami"
      ],
      "infectiologist": [
        "Luz Ares",
        "Carlos Conception",
        "Maria Qyezada",
        "Olga Zilberstein",
        "Wayne Joseph",
        "Chana Lieber"
      ],
      "cardiologist": [
        "Eric Behrens",
        "Pedro Corzo",
        "Farzana Flora, PA",
        "Chaudhary Ghumman",
        "Franklin Sencion",
        "Qaiser Abbas",
        "Louisa Ziglar",
        "Romina Tollerutti"
      ],
      "allergologists": [
        "Katie Carmen",
        "Michael Shirazi",
        "Yan Wang",
        "Laura Victor",
        "Patricia Pugni",
        "Maria Barbery",
        "Ramakrishna Karibandi"
      ],
      "urologist": [
        "Marie Dy-Guillaume",
        "Nicasio Arana",
        "Dov Landa",
        "Hari Polavarapu",
        "Michelle Ratau"
      ],
      "ophthalmologist": [
        "Carlos Gonzalez",
        "Jaime F. Roman",
        "Toni Aspinall-Daley",
        "Lori R. Hoch",
        "Polina Liss",
        "Jessica Huang",
        "Anita Ahuja",
        "Daniel Yadegar",
        "Jeffrey Ben-Zvi",
        "Chenna Reddy",
        "Givvi Lauren",
        "Igor Kirzhner",
        "LUIS GUERRERO"
      ],
      "oncologist": [
        "Maung Maung",
        "Kathleen McCabe",
        "Nam H Om",
        "Avi Bitton",
        "H. Robert Bearnot",
        "Olugbenga Dawodu",
        "Nina Priven",
        "Ydelfonso Decoo",
        "Francois Brutus",
        "Linli Yan-Rosenberg",
        "Jennifer Figueroa"
      ],
      "dermatologist": [
        "Devbala Ramanathan",
        "Jih- Ling Chiang",
        "Arkadiy Takhalov",
        "Gillian Katz",
        "Charles Chan",
        "Ramon Tallaj",
        "Beth Lustgarten",
        "Maurice Alwaya"
      ],
      "hematologist": [
        "Ruben Cerri",
        "Emilio Villegas",
        "Ramon Moquete",
        "Lauri Romanzi",
        "Theresa Wilson",
        "Rick Chou",
        "Rushita Patel",
        "Anna Suponya",
        "Drepaul Loris",
        "Baldevbhai V. Patel"
      ],
      "endocrinologist": [
        "Richard Neufeld",
        "Mary Stein",
        "Emily Jackness",
        "Eugene Dinkevich",
        "Bill Wagner",
        "Edward Geisler",
        "Chavannes Thomas"
      ]
    },
    "jackson heights": {
      "pulmonologist": [
        "Cherry Mar-Chan",
        "Richard Friedlander",
        "Batool Hussaini",
        "Shirishbhai Patel",
        "Kevin Myers",
        "Daniel Korin",
        "Robert Feldman",
        "Luiza Gusenon"
      ],
      "toxicologists": [
        "Jennifer Becker",
        "Joseph Marchisella",
        "Sohah Iqbal",
        "Jose Fulgencio Delmonte",
        "Wendy Ramirez",
        "Alice Riegel",
        "Kevin Charlotten",
        "Zil Goldstein",
        "Matthew Martinez",
        "Marie Garnes",
        "Stephen J. Kaiser",
        "Marcial Jimenez"
      ],
      "allergologists": [
        "Alexander Beylinson",
        "Robert Sarnataro",
        "Hajoon Chun",
        "Gonzalo Sabogal",
        "Moses Shalit",
        "Nirupama Somasundaram",
        "Brian Sumner",
        "Kelly Thompson",
        "Susan Dunn",
        "Douglas Birns",
        "Ilan Semandov"
      ],
      "infectiologist": [
        "David Pfaff",
        "Manuel Lopez",
        "Mario Haro",
        "Letha Daniel",
        "Herbert Chin",
        "Lidia Garcia",
        "Madhu Malhotra",
        "Hanna Lesicka M.D F.A.A.P., P.C.",
        "Nissar Shaikh",
        "Leticia Gonzalez .",
        "Madan Paul"
      ],
      "ophthalmologist": [
        "Salvatore Volpe",
        "Sultan Ahmed",
        "Gavriel Fuzaylov",
        "Titus Okunola",
        "Michael Terrani",
        "Abdul-Haki Issah",
        "Francisco Rosario",
        "William Shay",
        "Galina Kletsman",
        "Racquel M Volkowitz",
        "Veluy Chorm",
        "Ayman Hassan Elkhouly",
        "Alma Mesquita",
        "Samuel DeLeon"
      ],
      "nephrologist": [
        "Vijaya Lakshmi Chandrakant",
        "Jeffrey Chess",
        "Francisco Alonso",
        "Jose Ovalle",
        "Naghma Burney",
        "Bienvenido Fajardo",
        "Elsa J. Reyes",
        "Deqing Sun",
        "Eddy Vincent",
        "Angela Badiner",
        "Rahila Butt",
        "NABIL RAOOF"
      ],
      "rheumatologist": [
        "Sameet Palkhiwala",
        "Mikhail Pinkhasov",
        "Anu Kothari",
        "David Kaplowitz",
        "Todd McNiff",
        "Tak Yein Lim",
        "Allan Santiago",
        "Khader Rawand"
      ],
      "gastroenterologist": [
        "Meera Boppana",
        "Alfredo Maduro",
        "Rilee Chowlera",
        "Brett Wu",
        "Hector Florimon",
        "Lyudmila Sorkin",
        "Beverly Hurd",
        "Flora Lau",
        "Mercedes Blanche"
      ],
      "surgeon": [
        "Tarek Hegazi",
        "Kenneth Nordlicht",
        "Henry Ting",
        "Iwona Mienko",
        "Dilia Castanos",
        "Benjamin Wu",
        "Gardith Joseph",
        "Leon Kohanbasch",
        "Himanshu Patel",
        "Gerald Schulman",
        "Denise Nunez"
      ],
      "cardiologist": [
        "Joseph Louis",
        "Raymond Jones",
        "Giancarlo Guido",
        "Caesar Villarica",
        "Ghizlane Benchekroune",
        "Inna Gelfand",
        "Keisha Sinha",
        "Susheel Kodail",
        "VIRGINIA MARTINEZ",
        "Janette Torres",
        "Daniel Zakhary",
        "Thapvongse Chin",
        "Nina Huberman"
      ],
      "psychologist": [
        "Dalai Zhou",
        "Rafik Khaimov",
        "Dionicio Trejo",
        "Collier Chan",
        "Yan Wolfson",
        "Jonathan MT Chang"
      ],
      "dermatologist": [
        "Daysi Baez",
        "Shamim A. Begum",
        "Nikolai LaGoduke",
        "Rabeena Fazal",
        "Helen Na-Chuang",
        "Magdy Mohammed",
        "Demetra Eleftheriou",
        "Pei Ying Xiao",
        "Andrew Black",
        "Judah Charnoff",
        "Jacob George",
        "Katherine Gold",
        "Archana Saxena",
        "Kim Woods"
      ],
      "urologist": [
        "Yuchun Chen",
        "Genya Frid",
        "Altagracia Navarro",
        "Maximo D'Oleo",
        "Reucar Quijada",
        "Lili Ren",
        "Michael Raffinan",
        "Patricia Hart",
        "Michael M. Koegel",
        "Paul Krantz",
        "Jill Swenson",
        "Domingo Santana",
        "Jacob Esses",
        "Daniel Reich",
        "David Stein"
      ],
      "general practitioner": [
        "Adil Farooki",
        "Paul Leva",
        "Rohini Thodge",
        "Kara Fine",
        "Walt Sargeant",
        "Yelena Lindenbaum",
        "Thomas Fuchs",
        "Saimamba Veeramachaneni",
        "San San Wynn",
        "Alla Mesh",
        "Rahila Butt"
      ],
      "gynecologist": [
        "Dalia Frumkin",
        "Sarita Khatri",
        "Barry Weinberg",
        "Jeffrey Kwong",
        "Lucy Sourial",
        "Ira Blanfarb"
      ],
      "diabetologists": [
        "Sotirios Kassapidis",
        "Vishwanath Puttaswamy Gowda",
        "Jay Bassell",
        "Florence Pua",
        "Kevin O'Hara",
        "Julio Ramirez",
        "Nadja Pierre",
        "BREDY PIERRE-LOUIS MD",
        "Paul McClung",
        "REBECCA RAOOF"
      ],
      "endocrinologist": [
        "Hung-Sam Lee",
        "Sazia Setaruddin",
        "Maya Golbraykh",
        "Violeta Gomez",
        "Yelena Shedina",
        "Arthur Manning",
        "Ellen Blye",
        "Won S. Cho",
        "Futrell Junie",
        "Jubil Malieckal",
        "Michelle Schecter",
        "Tajammal Gilani"
      ],
      "pediatrician": [
        "Muntaz Majeed",
        "Joseph Grossman",
        "Jose Quiwa",
        "David Winter",
        "Roger Chung",
        "Sylvia Gonzales",
        "Donald Martinelli",
        "Pervaiz I. Qureshi",
        "Rummana Rahman",
        "Irene Shir",
        "Carol De Costa",
        "Max Bulmash",
        "Han Zhang",
        "Joseph Andrade"
      ],
      "hematologist": [
        "Devbala Ramanathan",
        "Richard Arias",
        "Sandra Gilban",
        "Gulam Khan",
        "Wilner Bonhomme",
        "Larisa Litvinova",
        "Jigar Patel",
        "Hui Chih Yang",
        "JUAN PILARTE"
      ],
      "oncologist": [
        "Kendy Verpile",
        "Israel Aviles",
        "Nancy L. Chiang",
        "Melissa Furman",
        "Marino Torres",
        "Andres Hernandez-Abreu",
        "O Jean Pierre",
        "Allan Plaut",
        "Sveltana Spivak"
      ]
    },
    "manhattan": {
      "dermatologist": [
        "Marianne LaBarbera, MD",
        "Petr Itzhak",
        "Dahua Zhou",
        "Harrison F. Mitchell",
        "Marcia Morgan",
        "Sumir Sahgal"
      ],
      "toxicologists": [
        "Austin Epstein",
        "Donna Seminara",
        "Jean-Robert Boursiquot",
        "Lynn A. Hawkins",
        "Keith Greenberg",
        "Richard Altman",
        "edward Mok",
        "Robert Vaccarino",
        "Genia Bekker",
        "Bola Olajide",
        "Jonathan Chang",
        "Julius Johnson",
        "Charles Nordin"
      ],
      "infectiologist": [
        "Paul C. Gazzara",
        "George Lum",
        "Hector Holson",
        "Dalsia Acosta",
        "Michael Frank",
        "Alan David",
        "Howard Hochster",
        "Jason Ogiste"
      ],
      "nephrologist": [
        "Ramy Hanna",
        "Subrahmanya Bhat",
        "Daniel Despen",
        "Lohrasb Ahmadian",
        "Indira Kairam",
        "Gunther Groning",
        "Caesar Mimieux",
        "Alyson Smith",
        "Aleska Pelaez-Acosta"
      ],
      "general practitioner": [
        "John Petrungaro",
        "Gopi Punukollu",
        "Yuderqui Checo",
        "Robert Meltzer",
        "Frances Dirks",
        "Todd Schlifstein",
        "Abdulla Alwani",
        "Jack Sadacka",
        "Fe T. Reyes-Arcangel"
      ],
      "pediatrician": [
        "Bart Savino",
        "Ahmad Kamal Aslam",
        "Lilliam Soto-Alcantara",
        "Chhaya Chakrabarti",
        "Cheng Gonjon",
        "Jilan Shah",
        "Yadiera Brown",
        "Olga Tseyko",
        "Carmen Co"
      ],
      "hematologist": [
        "Miguel Tirado",
        "Joseph Delimon",
        "Joseph Pierre",
        "Mario Lavelanet",
        "Mohammed Rashid",
        "Weimin Qu",
        "Mridula Dogra",
        "Doug Bailyn",
        "Dominick Bioh",
        "Richard Cedeno",
        "Thomas V. Tupper",
        "Adam Tonis",
        "Po Cheng Chu",
        "Ermany Castillon",
        "Belkis Colon"
      ],
      "urologist": [
        "Tooraj Zahedi",
        "Aisha Prim",
        "Sixto R. Caro",
        "Reza Chowdhury",
        "Jose Ortiz",
        "Lidia Garcia",
        "Irina Nelipovich",
        "Rodolfo Guzman"
      ],
      "surgeon": [
        "Jung-ah Han",
        "Zamar Raza",
        "Lucia Alva",
        "Jae Lee",
        "Frank Arbucci",
        "Maritza Archbold",
        "Tatyana Ledovsky",
        "Harry Gruenspan",
        "Elliot J Arons",
        "Larry Landphair",
        "Joseph Gelbfish",
        "Meir Kessler",
        "Calvin Lee",
        "Marie E. Lefevre",
        "Maria Soto",
        "Bentley Patterson",
        "Kishore Ahuja"
      ],
      "rheumatologist": [
        "Byung Kang",
        "Judith Jones",
        "Maria Del Carmen Hidalgo",
        "Margaret Clarke-Golden",
        "Michael Mazza",
        "Owen Golden"
      ],
      "allergologists": [
        "Michael Sands",
        "Mayer Ballas",
        "Eddie Yang",
        "Atkuri Subah"
      ],
      "gastroenterologist": [
        "Jesse Stoff",
        "Steve C Chang",
        "Yehuda Bar-Zvi",
        "Yomaris Pena",
        "Christina Chou",
        "Robin Frankel-Ovitsh"
      ],
      "cardiologist": [
        "Mamoun Alhajjouman",
        "Gerald Roberts",
        "Margaret Cheung",
        "Aysar B Fathallah-Mammo",
        "Robert Goodman",
        "Anming Luo",
        "Jerry Uduevbo",
        "Frank Arbucci",
        "Stellios Trikounakis"
      ],
      "endocrinologist": [
        "Farzana Aziz",
        "Shen-Han Lin",
        "Gonzalo Urbano",
        "Rekha Mahale",
        "Sindhu Gupta",
        "Mohsani Hossain",
        "Raphael Novogrodski"
      ],
      "pulmonologist": [
        "Kira Gelfenshteyn",
        "Dong Hong Shong",
        "Amy Su",
        "Catherine Alikor Mpi",
        "MARGARET KEARNS-STANLEY",
        "Gustavo Insignares",
        "CHARLES HWU",
        "Joseph Caruana",
        "Shafiqur Rahman",
        "Chaim Wanounou",
        "Donna Henry",
        "Jude Arthur"
      ],
      "gynecologist": [
        "Jovan Milos",
        "Marlene Rodriguez",
        "Angela Todd",
        "Melissa Chan",
        "Dov Grant",
        "John Mark",
        "Tien-Tsai Tsai",
        "Karen Weisz",
        "Igor Kletsman",
        "Peter Ruzohorsky",
        "Eric Bates",
        "Amit Saxena"
      ],
      "diabetologists": [
        "Rafael Rodriguez",
        "Ella Zavolunova",
        "Nicolas Rossetti",
        "Betty Mercedes",
        "Jacques Antoine",
        "Robin Chan",
        "Sheldon Lippman",
        "George McMillan",
        "Michel Lesly",
        "G Sahni"
      ],
      "ophthalmologist": [
        "Xianyang Yio",
        "David Hurwitz",
        "Claudia Useda",
        "Rita Khanijou",
        "SREENIVASA MURTHY"
      ],
      "psychologist": [
        "Eman Soultan",
        "Maksudul Chowdhury",
        "Robert Mayes",
        "Ida Ellen Schwab",
        "Gang Meng",
        "Li-Min Yang",
        "Charles Francis",
        "Amir Mayer",
        "Edwin Quinones"
      ],
      "oncologist": [
        "Beppy Edasery",
        "Ma Jesusa Christina Calagos",
        "Wenjing Tao",
        "Vincent Esposito",
        "Jayant Gandhi",
        "Faina Akselrod",
        "Usukumah E. Usukumah",
        "Samuel Bekar",
        "Laura Bruno",
        "Ferdousi Khan",
        "Tinmar Tun",
        "Sean Byrne"
      ]
    },
    "new york": {
      "pediatrician": [
        "Mun Hong",
        "Shaheen Ahmed",
        "Kimberly Green-Mayer",
        "Elliot Belenkov",
        "Nicholas Cannone",
        "Robert Romanoff",
        "Yvonne Essandoh",
        "Marjorie Ordene",
        "Marina Oks",
        "Elana Altzman",
        "Ewa Gawlik",
        "David Weiss"
      ],
      "infectiologist": [
        "Sydney Chen",
        "Jamilah Grant-Guimaraes",
        "Mario Peichev",
        "Luis E. Moquete",
        "Krisczar Bungay",
        "Lawrence Hitzeman",
        "Andrew Tzellas",
        "Wesner Moise",
        "HANI HABIB",
        "Madhu Rajaram",
        "Vera Antonios",
        "Alan Diaz"
      ],
      "endocrinologist": [
        "Billy Geris",
        "Nadia Martinez de Pimentel",
        "Salvador Perez",
        "Ingrid Felix-Peralta",
        "Emilio Villegas",
        "Alain Fedida",
        "Eleanor Lai",
        "Stuart Lewis",
        "Iris Sherman",
        "Nicholas DuBois",
        "Limeng Wang",
        "Gabor Menczelesz",
        "Altaf Khan",
        "Zaric Maja",
        "Patricia Halton",
        "Tosan Oruwariye"
      ],
      "urologist": [
        "Miroslawa Kudej",
        "Alberto Marcano",
        "Olukayode Ojutiku",
        "Dilruba Nabi",
        "Hector Florimon",
        "Raisa Slootsky",
        "Claudia Cooke",
        "Frank Spinelli",
        "Charles Gordon",
        "Gunjeet Sahni",
        "George Moskowitz",
        "Jack Apelbaum",
        "Jacob George",
        "Sudhakar Bhagavath",
        "Angela Davydov",
        "Julissa Baez"
      ],
      "diabetologists": [
        "Larisa Malisova",
        "Yeahseon Bruinings",
        "Sergio A. Martinez",
        "Juan A. Medina",
        "Michael Richter",
        "Steven J. Goldstein"
      ],
      "pulmonologist": [
        "Michael Moretti",
        "Ramon Pimentel",
        "Kee Shum",
        "Gunther Groning",
        "Albert Levy",
        "Steven Field",
        "Marilyn Jackson",
        "Joseph Poon",
        "Henghe Tien",
        "Janet Collins",
        "Steve T. Ayanruoh",
        "Jerome Cariaso",
        "Yanfeng Chen",
        "Goldie Schwarzbard",
        "John C. Riggs",
        "Jorge Cornielle",
        "Anil Gupta"
      ],
      "nephrologist": [
        "Nancy Wallach",
        "Sandra Robinson",
        "Rabeya Chowdhury",
        "Emeka E. Okeke",
        "Robert Meltzer",
        "Rushita Patel",
        "Dana DeVito",
        "Jack Levine"
      ],
      "toxicologists": [
        "Asbar Haaris",
        "YUMEI DING",
        "Todd Cowdery",
        "Meron Kristos",
        "Vidya Valada",
        "Ernst Ducena"
      ],
      "dermatologist": [
        "Lina Hwang",
        "Mitchell Kaphan"
      ],
      "gynecologist": [
        "SABINA AWWAL",
        "Oluwatoyosi Dairo",
        "Florence Golamco",
        "Shivani Paliwal",
        "Pamela Mahmud",
        "Henry Bellutta",
        "Harvey Benovitz",
        "Jeffrey Graf",
        "Craig Metroka",
        "Jean Paul Salinas",
        "Sara Buros",
        "Nedal Samarneh",
        "Melaine McLean"
      ],
      "hematologist": [
        "Luis Blanco",
        "Bella Sandler",
        "Meenu Gupta",
        "David Steiner",
        "David Kaplovitz",
        "Rogelio Lucas",
        "Gabrielle Severe",
        "Henry Sardar",
        "Enrique Pagan",
        "Paula Carugno"
      ],
      "surgeon": [
        "Daniel Buff",
        "Godwin Onyeike",
        "Ted Du",
        "Howard Grossman",
        "Muhammad K Qadri",
        "Grace Wright",
        "Sylvia Cotto",
        "Zaheer Ahmed",
        "Michael Hannan",
        "Melissa Hutt",
        "Dalan Sow Read",
        "Taiye Apoeso"
      ],
      "psychologist": [
        "Fausto Gonzalez",
        "Dharamjit N. Kumar",
        "Dan Krauser",
        "Gabriel Sagles",
        "Clifford Stark",
        "Jose Vargas",
        "Fievre Garnes Marie",
        "Wipanee Phupakdi"
      ],
      "ophthalmologist": [
        "Steve Hou",
        "Edison Ruiz",
        "Jilan Shah",
        "Temitope Jose",
        "Jose Goris",
        "Rameen Hashemiyoon"
      ],
      "allergologists": [
        "Paul Mantia",
        "Nadia Martinez de Pimentel",
        "Claudia Ravins",
        "Sergey Prokhorov",
        "Carmina Rivera",
        "Sushama Mody",
        "Gino Zunino",
        "Joseph Grossman",
        "Uzma Chatha",
        "Renae Bright",
        "Feliks Tsatskin",
        "Joseph Mintah",
        "Philip Owusu-Ansah",
        "Vinay Shah"
      ],
      "gastroenterologist": [
        "Diego Ponieman",
        "Lawrence Rosman",
        "Jingling Tang",
        "AnnMarie Yu",
        "Tuyen Trinh",
        "Atul Chokshi",
        "Eva Gomolinski",
        "Alfonso Ortiz",
        "Muhammad Adam",
        "Luisa Perez"
      ],
      "rheumatologist": [
        "Xin Tan",
        "Bahram Alyeshmerni",
        "Melville Hughes",
        "Man Yee Tong",
        "Larry Bishop",
        "David Kim",
        "Sirisha R. Tikko",
        "Hanbin Zheng",
        "Arnold Berlin",
        "Moshe Kerstein",
        "Raphael Novogrodsky",
        "Arpita Datta"
      ],
      "oncologist": [
        "Angela Meikle",
        "Antonia Subletas Mayol",
        "Coralys Vega",
        "Shu Yain Chin",
        "Dina Louie",
        "Jose Jerez",
        "Michael Lavianlivi",
        "Iftikhar Din",
        "Norman Greeley",
        "Anil Saxena",
        "Gillian Haans"
      ],
      "general practitioner": [
        "Alan Katz",
        "Luis Vasquez",
        "Peter Lo",
        "Bassam Aldaia",
        "Darren Esposito",
        "Karen Greer"
      ],
      "cardiologist": [
        "Scott Hartman",
        "Elizabeth Cruz",
        "Suzanne Flower",
        "Elliot Rayfield",
        "Rafael Bueno",
        "Diana Wynt",
        "Mariyum Shakir"
      ]
    },
    "queens": {
      "dermatologist": [
        "Jean Pierre Barakat",
        "Alma Mesquita",
        "Bruce Chung",
        "Sheila Cain",
        "Mark Schiffer",
        "Gerard Lombardo",
        "Luis Ortiz",
        "BABU PATEL",
        "Yves Verna"
      ],
      "diabetologists": [
        "Renata Ukowska",
        "Farzana Aziz",
        "Sergio A. Martinez",
        "Haque Naghmana",
        "Changhee Paek",
        "Muhammad Haque",
        "Carol Roye",
        "Mark Tsinker",
        "Mukund Mody",
        "Joshua Pollacil"
      ],
      "pediatrician": [
        "Igor Ryndin",
        "Farooq Umar Qureshi",
        "Jonathan Mohrer",
        "Rosa Gonzalez-Freire",
        "Qurrath Ain",
        "Keith Joseph",
        "Aldo Torrente",
        "Tina Wong",
        "Kenneth Altabef",
        "Paul Romanello",
        "Melina Mejia",
        "Zewge Deribe",
        "Richard Izquierdo",
        "Rasik Lal Patel"
      ],
      "infectiologist": [
        "Aaron Freilich",
        "Jay Kripalani",
        "Jacqueline Dumornay",
        "Ricardo Pou",
        "Jeffrey Kee Low",
        "Hong Ye",
        "Frank Maselli",
        "Robert Sable"
      ],
      "endocrinologist": [
        "Lainie Hurst",
        "Aran Degenhardt",
        "Nadge Coupet",
        "Roberto Moran",
        "Carl Casimir",
        "Rui Er Teng",
        "David Treatman",
        "Rattanjit Kohli",
        "Steven Siegal",
        "Marie France Conde",
        "Yechiel Zagelbaum",
        "Venkata Ravi",
        "Cynthia Sudar Singh Prabahar",
        "Gloria Murray",
        "Mandy Marantz",
        "Mohammad Azam"
      ],
      "gynecologist": [
        "Alvaro Olayo",
        "Derily Heredia",
        "Ing-Yann Jeng",
        "Dalia Olivier",
        "Lisa Minsky-Primus",
        "SUSAN MARGOLIS",
        "Huifang Xiao",
        "Wilfred Herard",
        "Stephen Zinnanti"
      ],
      "ophthalmologist": [
        "Mohammed Osmani, MD",
        "Khin Aung",
        "Pedro Corzo",
        "Baruch Kassover",
        "Robert Yu",
        "Adegboyega T. Adebayo",
        "Ian Lustbader",
        "Todd Mcniff",
        "Jean Zheng",
        "Tziporah Thall"
      ],
      "urologist": [
        "Ambrose Pipia",
        "Francisco Bautista",
        "Jessica Rubinstein",
        "Nahar Most",
        "Masoud Moarefi",
        "Donna Ingram",
        "Inna Gordin",
        "Shira Kaplovitz",
        "Stephan Simons"
      ],
      "surgeon": [
        "Michele Reed",
        "Tasbirul Alam",
        "Lionel Barrau",
        "George Liu",
        "Lomane Legros",
        "Costas Frousios",
        "Habib Nazarian",
        "Afamefune Onejemie",
        "Mitchell Seidman",
        "Hosneara Masub",
        "Ndeye Kone",
        "Julio Ramirez",
        "Yoram Amsalem"
      ],
      "oncologist": [
        "Rojasudha Vatti",
        "Farzana Nizami",
        "Alain Sosa",
        "Betty E. Stewart",
        "Victor Bulnes",
        "Charles Paolino",
        "Christiana Nichols",
        "Fayez Guirguis",
        "Michael Abbey-Mensah",
        "Aleksander Shalshin"
      ],
      "gastroenterologist": [
        "Xiaoxia Zhang",
        "Khaleeq Arshed",
        "Ming Zhu",
        "Geddis Abel-Bey",
        "Florentino Reyes",
        "Ya-Hsiu Yen",
        "Jose de Leon",
        "Edward T. Fitzpatrick",
        "Ala-May Lumibao",
        "Loris Omesh Drepaul",
        "Arthur Hall"
      ],
      "cardiologist": [
        "Marco A. Benitez",
        "Vikas Varma",
        "Richard Francisco",
        "Jianlin Wu",
        "Hyunsoon Beatrice Im",
        "Ilora Rafique",
        "Stephan Simons"
      ],
      "psychologist": [
        "Emerth L. Coburn",
        "Richard L. Francisco",
        "Rita Goldvug",
        "Lance Rubel",
        "Smita Biswas",
        "Samina Raghid",
        "Selman Leticia Vargas",
        "Yolanda Tun-Chiong",
        "Roberto Gabitto",
        "Maria Gomez",
        "Bingjing Roberts",
        "Sam Weissman",
        "Jacquelin Belamy",
        "Mohamed Azam"
      ],
      "allergologists": [
        "Richard Desmond",
        "Intazam Khan",
        "Teresa Chan",
        "Ward Carpenter",
        "Laszlo Feher",
        "Patrick Hu",
        "Yelena Havryliuk",
        "Hui Fang Xiao",
        "Chinta Chiu",
        "Rosemary Jackson",
        "Reina Eisner"
      ],
      "general practitioner": [
        "Sellathurai Dhayaparan",
        "JYOTI GANDHI",
        "Anna Zhivotovsky",
        "Robert Cohen",
        "Yevgeniya Kaykova",
        "Alan Lee",
        "Xinru Qian",
        "Maxine Orris",
        "Reynaldo Alonso",
        "Jun Kang",
        "Editha Figurasin"
      ],
      "pulmonologist": [
        "Perry Frankel",
        "Swarn Gupta",
        "Zia Ahmed",
        "Chun Kit Chan",
        "Eileen Chen",
        "Marissa Pelletier",
        "Patria Gonzalez",
        "Jay Bienenfeld",
        "Edwin Quinones"
      ],
      "nephrologist": [
        "Anuja Reddy",
        "Max Jean-Gilles",
        "Gregorio Hidalgo",
        "Jack Resnick",
        "Michael Strongin",
        "Olusegun Adeonigbagbe",
        "Dalia Yadegar",
        "Lamont Freeman",
        "CHAULA PATEL"
      ],
      "rheumatologist": [
        "Sidney Rosman",
        "Andrew Maran",
        "Violeta Gomez",
        "Federico Pichardo",
        "Andres Pereira",
        "Angela Davydov",
        "Mehmet Cetin",
        "Maria Del Carmen Hidalgo"
      ],
      "toxicologists": [
        "Khutoretsky Igor",
        "Saroj Gupta",
        "Martin Baskin",
        "Rainer Mittl",
        "Jean Robert Macenat",
        "Delsa Compres"
      ],
      "hematologist": [
        "France Lee",
        "Khalid Chaughtai",
        "Agnes So",
        "Olufunmilayo Adeyanju",
        "Emancia Neil"
      ]
    },
    "staten island": {
      "ophthalmologist": [
        "Inna Bukharovich",
        "Mohammad Bhatti",
        "Michele Reed",
        "Gerson Gomes",
        "Yuan Yi Li",
        "Marissa Santos",
        "Fabio Mehrgut",
        "Jose Mendez",
        "Norayr Baboumian MD",
        "Gregorio Hidalgo",
        "Felix Rodriguez",
        "Jacob Meltzer",
        "Teresita Go",
        "Elna Tamayo-Prado",
        "Robert Bressner",
        "Aline Shehigian"
      ],
      "urologist": [
        "Rita Grigiene",
        "Richard Wang",
        "Etan Kurland",
        "David Woldenberg",
        "Amy Bloomgarden",
        "Katherine Teets Grimm",
        "Heuscent James",
        "Mario Manna",
        "Maha Awikeh",
        "Ashley Ray",
        "Chrystian Belliard",
        "Kenneth Nyer"
      ],
      "cardiologist": [
        "Keith Kouroupos",
        "Jing Jing Dong",
        "Josefa Grech",
        "Howard Hinestroza",
        "JUAN ALBA",
        "David Baskin",
        "Manuel Sy",
        "Ashok Sinha",
        "Chaudhry Ghumman",
        "FOUZIA SYED",
        "Eric Jerome",
        "Shira Selevan",
        "Dassa Gabriel"
      ],
      "allergologists": [
        "John McCarthy",
        "Myo Maw",
        "Rany Condos",
        "Marlene Pitamber",
        "Jose Fibrellet",
        "Robert Segal",
        "James Pacholka",
        "Seth Kurtz"
      ],
      "nephrologist": [
        "Paolo Perrone",
        "Sophia Streete-Smalls",
        "Carlos Melendez",
        "Asadur R Miah",
        "Indranil Gupta",
        "Luis Blanco",
        "Mikhail Paikin",
        "Jennifer Cheng",
        "Ingrid Williams",
        "Annabi Djalo"
      ],
      "toxicologists": [
        "Svetlana Ten",
        "Mariela Jimenez",
        "Eduard Levy",
        "Nemaan Ghuman",
        "Jeffrey Goldstein",
        "Allen M. Kaufman",
        "Theresa Pondok",
        "Stuart Goldwasser",
        "Patricia Gregory",
        "Olive Osborne"
      ],
      "pediatrician": [
        "Joel Baum",
        "Deborah Martin-Arila",
        "Naum Meyerovich",
        "Modi Phiroza",
        "Pedro Guzman",
        "Jean-Robert Boursiquot"
      ],
      "hematologist": [
        "Mergie Desir",
        "Karin Kalkstein",
        "Darnley Renaud",
        "Khalil Solaimanzadeh",
        "Zili He",
        "Haiyan Lu",
        "Stephen Hofmeister",
        "Alicia Massop-Flowers",
        "Henry Chen"
      ],
      "gynecologist": [
        "Allan Detweiler",
        "Sameer K Misra",
        "Salamat Majeed",
        "Andrew Bohmart",
        "Kenneth Tam",
        "Dana Jacobs",
        "David Brick",
        "Liliya Drukman",
        "Jimmy Sitt",
        "Karen Rigor Tarite"
      ],
      "psychologist": [
        "James Flesher",
        "Michael Tugetman",
        "Jiansheng Zhao",
        "Manuel R. Esteban-Galindo",
        "Nick Gianoukakis",
        "Robin Campos",
        "Kecia Gerlach",
        "Garman Ho",
        "Alyssa Siegel",
        "Norman Klein",
        "Joseph Ahram"
      ],
      "gastroenterologist": [
        "Punyadechi Photangtham",
        "Shazia Sami",
        "Derek Liang",
        "Martha Valdivia",
        "Ransford Newhad",
        "Jose Aponte",
        "Narayana Byagari",
        "Florence Golamco",
        "George Owusu"
      ],
      "rheumatologist": [
        "Barbara Berger",
        "Ira Casson",
        "Karen Adamson",
        "Shiva Golshan",
        "Earl Ellis",
        "Bhavana Japi",
        "Prasanta Chandra",
        "Edna Anne Pytlak",
        "Ajith Karayil",
        "Frank Arbucci"
      ],
      "infectiologist": [
        "Nazia Ajani",
        "Leon Scrimmager",
        "Edward A. Nichols",
        "Josef Shimonov",
        "Albert Bassoul",
        "Masoud Moarefi"
      ],
      "oncologist": [
        "Daysi Baez",
        "Vi Quach",
        "Jose Serruya",
        "Daljeet Singh",
        "Cluny Lefevre",
        "Sunanda Chugh",
        "Howard Grossman",
        "Nagi Bustros",
        "Deepak Amin",
        "Charles Jean Cloude",
        "Seth Kurtz",
        "Ali Saleh"
      ],
      "general practitioner": [
        "Marie Belotte",
        "Gary Guarnaccia, MD",
        "Michelle Senbertrand",
        "Faisal Ali",
        "Valeriy Chorny",
        "Cecilia Calderon",
        "Rosario Reyes-Rigor",
        "Francis Hayden"
      ],
      "surgeon": [
        "Alexander Choi",
        "Barnali Hasan",
        "Larisa Khesina",
        "Daniel St-Pierre",
        "Syed Ahmad",
        "Christopher Kacin",
        "Adenike Adeyemo",
        "Maria Diaz"
      ],
      "dermatologist": [
        "Afzal Hossain",
        "Gretchen Throner",
        "Rong Xu",
        "Christine Rodler"
      ],
      "endocrinologist": [
        "Kyungmee Kim",
        "Daniel Reinharth",
        "Alejandra Wilson",
        "Keyan Ma",
        "Fermin P. Gonzalez",
        "Michael Eidelman",
        "Liana Dao",
        "Ramon Delmonte",
        "Ritu Davis",
        "Betty Mercedes",
        "Chidiadi Ododo"
      ],
      "diabetologists": [
        "David Magier",
        "Lorraine Williams",
        "Nicasio Arana",
        "Victor Peralta",
        "Juan Chabla",
        "Rahul Solanki",
        "Bisher Akil",
        "Rosa Gamundi-Joaquin",
        "Judy Honig",
        "Chaya Wald",
        "Olusanya Rufai",
        "Bella Binik",
        "Elizabeth Lee-Rey"
      ],
      "pulmonologist": [
        "Lyudmila Oslon",
        "Rita P. Verna",
        "Jin Wang",
        "Ruben Carvajal",
        "Lourdes Aguayo"
      ]
    }
  }